### ISSUE TITLE
USER STORY: Landing Page

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/take-control-frontend-app#1]
As a new user, I can instantly see information about the application, so that I can understand the value that it may offer me.

## Acceptance Criteria

1. Favicon of app logo
2. App Logo and name stand out as the main title
3. "Keep all your plates spinning" slogan stands out
4. Clear information about the app provided
5. Images display are specific to whether the user is displaying the page on mobile or desktop
6. Bottom of the screen takes user to the sign up
7. Footer provides info about development of the app

## Tasks

- [x] Add Favicon
- [x] Create footer component
- [x] Add footer content (shorten for mobile)
- [x] Style footer
- [x] Check and adjust general page styling
- [x] Create home component
- [x] Add landing page content
- [x] Add and link up call to action buttons
- [x] Style home
- [x] Check responsivity
- [x] Test on deployed site

**Comment by GeorginaCarlisle** [comment]
All tasks completed. However, issue to be left open and returned to further on in development when extra info, such as screenshots can be added.
