### ISSUE TITLE
USER STORY: Sign-in page

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/take-control-frontend-app#10]
As a signed-up user, I can use my username and password to sign in to my account, so that my account remains secure and only I can login.

## Acceptance Criteria

1. A link to sign in is present in the Navbar for non-authenticated users.
2. Link takes the user to the sign in page.
3. Clear page title.
4. Sign in form with clear labels to aid completion.
5. Errors in form input fields are clearly displayed back to the user.
6. Successful completion takes user to the home page, which welcomes them and provides call to action buttons to 'plan' and 'take action'.

## Tasks

- [x] Add Signin component file
- [x] Import Button, Form and Page css modules
- [x] Import component into App.js as part of routing
- [x] Add form component from React bootstrap
- [x] Add content and edit component
- [x] Add any custom css
- [x] Add variables to be handled by useState hook and destructure if needed
- [x] Add handleChange function
- [x] Add handleSubmit function
- [x] Add error handling
- [x] Add logic to render homepage depending on user status
- [x] Test on deployed site

**Comment by GeorginaCarlisle** [comment]
All tasks completed and acceptance criteria met.
