### ISSUE TITLE
USER STORY: Current user context

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/take-control-frontend-app#11]
As a signed-up user, I am the only one who can access my data, so that it remains safe and secure.

## Acceptance Criteria

1. Current user data is accessible to all pages and components, so that everything is rendered appropriately for the current user.

## Tasks

- [x] Set up current user context which gets and sets the current user and returns providers for these.
- [x] Import into index.js and use to wrap app.
- [x] Add to signin and on sign in set the current user.
- [x] Test to check current user context is functioning as expected.
