### ISSUE TITLE
USER STORY: Log out

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/take-control-frontend-app#13]
As an authenticated user, I can easily logout of my account, so that I can keep my account secure.

## Acceptance Criteria

1. Authenticated users are provided with a clear link to sign out in the navigation bar.
2. Clicking sign out will sign the user out and return them to the home page.

## Tasks

- [x] In NavBar.js create a function to handle signing out, this should include updating the CurrentUser.
- [x] Add on click attribute to Signout link which calls the handle signout function.
- [x] Check working locally
- [x] Check working on live deployed site

**Comment by GeorginaCarlisle** [comment]
All tasks completed and acceptance criteria met.
