### ISSUE TITLE
USER STORY: Focus - create

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/take-control-frontend-app#17]
As an authenticated user, I can create focus areas, so that I can set out the different areas in my life that I want to use this app to support with and why each area is important to me.

## Acceptance Criteria

1. Clicking the button to add new focus, within the plan page, takes me to the create focus form.
2. Title confirms I am in the correct place to create a new focus.
3. Form has clear labels to aid completion.
4. Errors in form input fields are clearly displayed back to me.
5. Successful completion creates a new focus and takes me to a page where I can add goals and tasks to my focus.
4. At any point I can cancel and return to the plan page.

## Tasks

- [x] Create FocusCreate component
- [x] Add to routing
- [x] Add main content
- [x] Add form
- [x] Edit form and styling
- [x] Add state to handle changes to form
- [x] Add cancel button which directs back to plan
- [x] Handle errors and display back to the user
- [x] Handle submission of the form directing to form page
- [x] Check working locally
- [x] Check working on deployed

**Comment by GeorginaCarlisle** [comment]
All tasks completed and acceptance criteria met.
