### ISSUE TITLE
USER STORY: Focus - edit

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/take-control-frontend-app#18]
As an authenticated user, I can edit a focus area, so that I can make changes should I wish.

## Acceptance Criteria

1. When viewing a focus I can click on an edit button.
2. I can view my current focus details in a form.
3. I can edit each of the details.
5. Clicking to save updates my focus details and returns me to the focus view.
6. I can click cancel at any point to return to the focus view without saving.
7. I am informed of any errors in my inputs.

## Tasks

- [x] Create intermediatory focusArea component that will hold focusview + edit + delete
- [x] focusArea will hold focusData and focus_state and map these into relevant nested component.
- [x] Create focusEdit component.
- [x] Link up edit button in focus view.
- [x] Add content and style to focusEdit.
- [x] Handle form changes
- [x] Handle submit
- [x] Handle cancel
- [x] Test locally
- [x] Test on deployed

**Comment by GeorginaCarlisle** [comment]
All tasks completed and acceptance criteria met.
