### ISSUE TITLE
USER STORY: Focus - delete

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/take-control-frontend-app#19]
As an authenticated user, I can delete a focus area, so that I can remove information I no longer need or want.

## Acceptance Criteria

1. When viewing a focus area there is a button to delete.
2. On clicking to delete I am presented with a confirmation message.
3. I can then confirm or cancel the delete request.
4. On cancel I am returned to the focus view.
5. On delete, the focus area is deleted and I am returned to the main plan.

## Tasks

- [x] Create FocusDelete and nest into focus area
- [x] Wire up delete button in focus view
- [x] Add content and style
- [x] Wire up cancel button
- [x] Handle confirm with API call and return to plan
- [x] Test locally
- [x] Test on deployed

**Comment by GeorginaCarlisle** [comment]
All tasks completed and acceptance criteria met.
