### ISSUE TITLE
USER STORY: Goal delete

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/take-control-frontend-app#23]
As an authenticated user, I can delete a goal, so that I can remove information I no longer need or want.

## Acceptance Criteria

1. When viewing a goal there is a button to delete.
2. On clicking to delete I am presented with a confirmation message.
3. I can then confirm or cancel the delete request.
4. On cancel I am returned to the goal view.
5. On delete, the goal is deleted and I am returned to the main focus view with no goal selected.

## Tasks

- [x] Create GoalDelete and nest into goalsection and goalindividual.
- [x] Wire up delete button
- [x] Add content and style
- [x] Wire up cancel button
- [x] Handle confirm with API call and removal of goal from goals, removal of goal_id from keyParameters and change of goalstate to view (in desktop).
- [x] Test locally
- [x] Test on deployed

**Comment by GeorginaCarlisle** [comment]
All tasks completed and acceptance criteria met.
