### ISSUE TITLE
USER STORY: Task - edit

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/take-control-frontend-app#27]
As an authenticated user, I can edit a task, so that I can make changes should I wish.

## Acceptance Criteria

1. All tasks viewed in the planning section of the site have three dots next to them.
2. Clicking on the three dots brings up a list of options including edit.
3. Clicking to edit transforms the view of the task into an edit form.
4. I can make changes to my task details.
5. At any point I can click cancel transforming the view back to normal.
6. Clicking submit edits my task and transforms the view back to normal with all changes in place.

## Tasks

- [x] Create Task Individual to hold all the switching functionality.
- [x] Create TaskEdit component.
- [x] Create option list and wire up to three dots.
- [x] Wire up clicking edit to open taskedit.
- [x] Add edit form and style.
- [x] Wire up all functionality for the edit form.
- [x] Test locally.
- [x] Test deployed.

**Comment by GeorginaCarlisle** [comment]
All tasks completed and acceptance criteria met.
