### ISSUE TITLE
USER STORY: Task - delete

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/take-control-frontend-app#28]
As an authenticated user, I can delete a task, so that I can remove information I no longer need or want.

## Acceptance Criteria

1. All tasks viewed in the planning section of the site have three dots next to them.
2. Clicking on the three dots brings up a list of options including delete.
3. On clicking to delete I am presented with a confirmation message.
4. I can then confirm or cancel the delete request.
5. On cancel I am returned to the task view.
6. On delete, the task is deleted and removed from the task list.

## Tasks

- [x] Create TaskDelete and nest into taskindividual.
- [x] Add delete to task choices and wire up
- [x] Add content to task delete and style
- [x] Wire up cancel button
- [x] Handle confirm with API call and removal of task from tasks.
- [x] Test locally
- [x] Test on deployed

**Comment by GeorginaCarlisle** [comment]
All tasks completed and acceptance criteria met.
