### ISSUE TITLE
USER STORY: Focus page

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/take-control-frontend-app#31]
As an authenticated user, I can view all the goals and tasks within a given focus area together, helping me to plan how I wish to move forwards in this area and everything that is need to achieve that progression.

## Acceptance Criteria

1. Clear title lets me know where I am.
2. Clicking on the X in the top right takes me back to the main plan page.
3. Information about the Focus is clearly displayed at the top, with options to edit and delete.
4. All goals and day to day tasks linked to the focus are shown with options to add, edit and delete.
5. On desktop, the goal titles are listed with space to expand one of the goals, showing all information and nested tasks.
6. On mobile, day-to-day tasks, goals and their nested tasks are displayed in an accordion.
7. Borders, white spacing and titles clearly separate out the information.

## Tasks
- [x] Create Focus page
- [x] Include in routing and add links from main plan and focus create
- [x] Create separate mobile and desktop components
- [x] In desktop add grid structure and placeholders
- [x] In Mobile Add space for focus info and accordion for other sections with placeholders.
- [x] Create FocusView file that pulls into mobile and desktop components.
- [x] Pass in any props and handle.
- [x] Add content and style.
- [x] Make an api request for focus details and render.
- [x] Wire up X.
- [x] Create taskList component that pulls into mobile and desktop components.
- [x] Pass in any props (including whether day-to-and handle.
- [x] Create taskview component that pulls into tasklist.
- [x] Add content and styling for tasklist and taskview.
- [x] Make an api request to tasklist and map results into taskview.
- [x] Adjust styling
- [x] Create goalsection component that pulls into focusdesktop
- [x] Add content and style
- [x] Make an api request in goal section that maps the list of goals
- [x] Decide on best course of action for mobile view
- [x] Create goalsection mobile that gets goals and maps them 
- [x] Create goalview component that pulls into goal section
- [x] Add content and style
- [x] Add functionality to render chosen goal in goal view
- [x] Add nested tasks to goal view
- [x] Adjust all styling
- [x] Test locally
- [x] Test deployed

**Comment by GeorginaCarlisle** [comment]
All tasks completed and acceptance criteria met.
