### ISSUE TITLE
USER STORY: Success messages

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/take-control-frontend-app#33]
As an authenticated user, I receive a success message on creation, editing and deleting, so that I know my action was successful.

## Acceptance Criteria

1. Every time I submit a form to create, edit or delete data a toast pops up.
2. The toast has a header of success.
3. The toast contains details of the action that has been performed.
4. The toast has an x that I can use to dismiss the message.
5. The toast automatically disappears after 8 seconds. 

## Tasks

- [x] Create toast in app.js to display successful signup.
- [x] Add state to control the toast.
- [x] Pass state into signup and update on successful sign up.
- [x] Add clearing of state on toast being dismissed.
- [x] Refactor code into a custom context.
- [x] Refactor Toast into its own component.
- [x] Set message on submit in focuscreate.
- [x] Set message on submit in actiontaskcreate. 
- [x] Set message on submit in taskcreate. 
- [x] Set message on submit in taskedit. 
- [x] Set message on submit in taskdelete. 
- [x] Set message on submit in focusedit. 
- [x] Set message on submit in focusdelete. 
- [x] Set message on submit in goalcreate.
- [x] Set message on submit in goaledit.
- [x] Set message on submit in goaldelete.
- [x] Set message on toggle today on/off in actiontask
- [x] set message on toggle done on/off in actiontask
- [x] Set message for end of day reset in Take Action.
- [x] Test locally
- [x] Test on deployed

**Comment by GeorginaCarlisle** [comment]
All tasks completed and acceptance criteria met
