### ISSUE TITLE
USER STORY: Take Action page

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/take-control-frontend-app#36]
As an authenticated user, I can view all active tasks together in a take action page, so that I can plan and organise my day.

## Acceptance Criteria

1. I can access the take action page directly from a link in the navigation bar and also from a call to action button in the signed in homepage.
2. A clear title informs me that I am in "Take Action".
3. A section titled backlog contains all my active tasks.
4. Each task has an image specifying which focus area it belongs to.
5. Each Task also specifies the goal it is attached (if this is the case) and any deadline information.
6. On mobile the backlog area can be opened or closed.

## Tasks

- [x] Create a takeaction component and link upto.
- [x] Create specific desktop and mobile components that are nested inside the main take action and rendered dependent on screen size.
- [x] Add overarching layout and placeholder text in mobile.
- [x] Add overarching layout and placeholder text in desktop.
- [x] Make an api call to get a list of active tasks
- [x] Create actiontask component and nest within backlog column.
- [x] Add content with placeholders and style.
- [x] Pass relevant props into actionTask.
- [x] Render passed data in action task and check styling.
- [x] Test locally.
- [x] Test on deployed.

**Comment by GeorginaCarlisle** [comment]
All tasks completed and acceptance criteria met.
