### ISSUE TITLE
USER STORY: Daily reset

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/take-control-frontend-app#37]
I can click to reset the Action page, deleting one-off completed tasks and returning everything else to the backlog, so that I can start afresh each day.

## Acceptance Criteria

1. When in the Take Action there is a button called "End of day reset"
2. Clicking the button brings up a confirmation message explaining the reset process
3. Clicking to cancel removes the confirmation message and no changes are made.
4. Clicking to reset deletes all achieved tasks, sets today to false for all today tasks and removes the confirmation message with all changes visible.

## Tasks

- [x] Create modal within TakeAction to display confirmation message
- [x] Wire up 'End of day reset" button
- [x] Wire up close model and cancel buttons
- [x] Wire up "Reset take action button" with all logic
- [x] Test locally
- [x] Test on deployed

**Comment by GeorginaCarlisle** [comment]
All tasks completed and acceptance criteria met.
