### ISSUE TITLE
USER STORY: NavBar component

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/take-control-frontend-app#4]
As a user, a clear navigation bar is present throughout the site, so that I can navigate easily between different sections of the application.

## Acceptance Criteria

1. Navigation bar fixed at the top of all pages.
2. Links are present to help the user navigate through the site.
3. The apps logo is displayed on the left and takes the user back to the home page.
4. On smaller screens the navigation links are accessed by clicking on a hamburger icon.
5. Navigation menu can be toggled off by re-clicking the hamburger icon or by clicking outside of the menu.
6. Navigation menu is automatically toggled off on the page changing.

## Tasks

- [x] Add NavBar component file
- [x] Import component into App.js
- [x] Add Navbar component from React bootstrap
- [x] Add content and edit component
- [x] Add custom css
- [x] Validate code
- [x] Test on deployed site

**Comment by GeorginaCarlisle** [comment]
All tasks completed and acceptance criteria met.
