### ISSUE TITLE
USER STORY: Order backlog tasks

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/take-control-frontend-app#40]
As an authenticated user, I can order tasks in the backlog by repeated, focus, deadline, most recent, least recent, day to day or goal, so that I can set up the backlog in a way that works for me.

## Acceptance Criteria

1. In the backlog section there is a selection box to provide ordering of the tasks.
2. This sits under the title in desktop and at the top of the expanded backlog section in mobile.
3. Clicking on the selection box brings up a list of ordering options.
4. Clicking an option causes the backlog list of tasks to order accordingly.  

## Tasks

- [x] Add select input with label and options into required location.
- [x] Handle changes made to the select input.
- [x] Make an api request when a changes is made to request for tasks ordered as selected.
- [x] Adjust styling.
- [x] Test locally.
- [x] Test deployed.

**Comment by GeorginaCarlisle** [comment]
All tasks completed and acceptance criteria met.
