### ISSUE TITLE
USER STORY: Add new tasks

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/take-control-frontend-app#41]
As an authenticated user, I can quickly add new tasks to the backlog without needing to go through the planning page, so that I can quickly and easily add additional tasks.

## Acceptance Criteria

1. When I am in "Take Action" there is a clear button to add an additional task.
2. Clicking the button opens an "Add New Task" Modal.
3. The modal contains a form to create a new task.
4. The form also includes a section to link to a focus area and if focus area linked a section to link to a goal.
5. I can then choose to cancel or submit.
6. Cancelling closes the modal.
7. Submitting creates a new task, closes the modal and my new task is visible in the backlog.

## Tasks

- [x] Create NewTask modal and wire up to button.
- [x] Add form.
- [x] Make request to get list of focus areas for focus choice menu
- [x] Add logic and request to get list of goals for chosen focus area
- [x] Handle changes to the form
- [x] Handle cancel
- [x] Handle submit
- [x] Test locally
- [x] Test deployed

**Comment by GeorginaCarlisle** [comment]
All tasks completed and acceptance criteria met.
