### ISSUE TITLE
USER STORY: Completed tasks

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/take-control-frontend-app#45]
As an authenticated user, I can toggle tasks as completed moving them to a completed list, so that I can see exactly what I have achieved.

## Acceptance Criteria

1. A section titled completed in the take action page contains all my tasks marked as completed.
2. All tasks in the today column have a done checkbox.
3. When the checkbox is toggled on the task disappears from today and appears in the completed column.
4. The checkbox is also present in the completed column and when toggled off the task is moved back.

## Tasks

- [x] Add checkbox to today tasks
- [x] Handle toggle on with a patch request and update tasks details by setActiveTasks
- [x] Adjust content and styling specific to being completed tasks.
- [x] Handle toggle off on completed tasks with a patch request and update tasks details by setActiveTasks
- [x] Test locally.
- [x] Test on deployed.

**Comment by GeorginaCarlisle** [comment]
All tasks completed and acceptance criteria met.
