### ISSUE TITLE
USER STORY: Specific logged in/logged out nav links

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/take-control-frontend-app#5]
As a user, the navigation bar contains links which are specific to whether I am logged in or logged out, so that all available links are relevant and accessible to me.

## Acceptance Criteria

1. Non authenticated users should find: about, signup and signin in the nav bar.
2. Authenticated users should find: take action, find, labels, profile and signout in the nav bar.
3. Non authenticated users trying to access (take action, find, labels, profile) will be redirected to the login page.
4. All links should work as expected.
## Tasks

- [x] Get current user from the CurrentUserContext
- [x] Separate the navlinks into two separate variables outside of the return statement
- [x] Use a ternary statement and currentuser to determine which variable should be rendered as part of the nav bar.
- [x] Add a ternary statement to all authenticated user only routes which redirects if no current user.
- [x] Check working locally
- [x] Check working on live site

**Comment by GeorginaCarlisle** [comment]
All tasks completed and acceptance criteria met.
