### ISSUE TITLE
TASK: Set up react framework

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/take-control-frontend-app#59]
## Acceptance Criteria

1. All main dependencies installed
2. App deployed and working as expected

## Tasks

- [x] Set Node to 16.19.1
- [x] Install dependencies from template
- [x] Edit app.js and check app runs as expected
- [x] Install React Bootstrap
- [x] Test to check bootstrap working as expected
- [x] Add dependency info to readme
- [x] Deploy to heroku
- [x] Add deployment info to readme
- [x] Check deployed app is working as expected

**Comment by GeorginaCarlisle** [comment]
All tasks complete and success criteria met.
