### ISSUE TITLE
TASK: Test and validate Authentication epic

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/take-control-frontend-app#62]
## Acceptance criteria

All user stories and functionality within the authentication epic fully tested, validated and documented.

## Tasks:
- [x] Validate JSX code
- [x] Validate CSS code
- [x] Test all views using lighthouse
- [x] Check color contrast tested
- [x] Test acceptance criteria for all user stories
- [x] Test form handling
- [x] Test responsivity across mobile, tablet, laptop and desktop
- [x] Test compatibility across safari, chrome, firefox and edge
- [x] Check through planning and note any changes
- [x] Write epic up in features, incl. screenshots, fully details and how features contrib to overall user experience.
- [x] Write up any features not implemented in future features

**Comment by GeorginaCarlisle** [comment]
All tasks completed
