### ISSUE TITLE
TASK: Test and validate backlog epic

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/take-control-frontend-app#69]
## Acceptance criteria

All user stories and functionality within the backlog epic fully tested, validated and documented.

## Tasks:
- [x] Test acceptance criteria for all user stories
- [x] Test responsivity across mobile, tablet, laptop and desktop
- [x] Test compatibility across safari, chrome, firefox and edge
- [x] Check through planning and note any changes
- [x] Write epic up in features, incl. screenshots, fully details and how features contribute to overall user experience.
- [x] Write up any features not implemented in future features

**Comment by GeorginaCarlisle** [comment]
All tasks completed
