### ISSUE TITLE
USER STORY: Link from take action tasks back to plan

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/take-control-frontend-app#8]
As an authorised user, clicking on a task within the ‘take action’ page will take me to the ‘plan’ page where that task is located.

## Acceptance Criteria

1. Clicking on the picture next to a task in Take action takes me to that focus area in the plan section.

## Tasks

- [x] Wrap the image in a link to the focus of the task.
- [x] Add hover functionality to the image
- [x] update back buttons to return to the previous page
- [x] Test locally
- [x] Test deployed

**Comment by GeorginaCarlisle** [comment]
All tasks completed and acceptance criteria met.
