### ISSUE TITLE
USER STORY: Sign-up page

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/take-control-frontend-app#9]
As a new user, I can easily set up an account, so that I can quickly get stuck into exploring and using the application.

## Acceptance Criteria

1. A link to signup is present in the Navbar for non-authenticated users.
2. A call to action button to signup is present on the landing page.
3. Links take the user to the signup page.
4. Clear page title.
5. Sign up form with clear labels to aid completion.
6. Errors in form input fields are clearly displayed back to the user.
7. Successful completion takes user to the login page.

## Tasks

- [x] Connect up frontend and API
- [x] Add Signup component file
- [x] Add and link css module
- [x] Import Button and Page css modules as well
- [x] Import component into App.js as part of routing
- [x] Add form component from React bootstrap
- [x] Add content and edit component
- [x] Add custom css
- [x] Add variables to be handled by useState hook and destructure if needed
- [x] Add handleChange function
- [x] Add handleSubmit function
- [x] Add error handling
- [x] Test on deployed site
